WebApplication1/Areas/Admin/Controllers/ProductMngController.cs
using WebApplication1.Models.bus;
using ShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles="Admin")]
    public class ProductMngController : Controller
    {
        public ActionResult Index(int? page)
        {
            page = page ?? 1;
            var ds = SanPhamBUS.DanhSachFull(page.Value, 25);
            return View(ds);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Loai = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            ViewBag.NhaSX = new SelectList(NhaSanXuatBUS.DanhSach(), "ID", "Ten");
            return View();
        }

        [HttpPost]
        public ActionResult Add(SANPHAM sp, HttpPostedFileBase HinhAnhChinh, IEnumerable<HttpPostedFileBase> HinhAnhPhu)
        {
            sp.NgayCapNhat = DateTime.Now;
            string mainImgName = SaveImg(HinhAnhChinh);

            if (!string.IsNullOrEmpty(mainImgName))
                sp.HinhAnh = mainImgName;

            SanPhamBUS.Add(sp);

            if (HinhAnhPhu != null && HinhAnhPhu.Count() > 0)
            {
                foreach (var img in HinhAnhPhu)
                {
                    string imgName = SaveImg(img);
                    if (!string.IsNullOrEmpty(imgName))
                        HinhAnhSpBUS.Add(sp.ID, imgName);
                }
            }

            ViewBag.Loai = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            ViewBag.NhaSX = new SelectList(NhaSanXuatBUS.DanhSach(), "ID", "Ten");
            return View();
        }

        [NonAction]
        public string SaveImg(HttpPostedFileBase img, string origin = "")
        {
            string name = "";
            if (img != null && img.ContentLength > 0)
            {
                if (string.IsNullOrEmpty(origin))
                    name = Guid.NewGuid().ToString() + img.FileName.Substring(img.FileName.LastIndexOf('.'));
                else
                    name = origin;
                var path = System.IO.Path.Combine(Server.MapPath("~/Content/images/products/"), name);
                img.SaveAs(path);
            }
            return name;
        }
        
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var sp = SanPhamBUS.ChiTietOri(id.Value);
            ViewBag.Loai = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            ViewBag.NhaSX = new SelectList(NhaSanXuatBUS.DanhSach(), "ID", "Ten");
            ViewBag.HinhAnhPhu = HinhAnhSpBUS.DanhSach(id.Value);

            return View(sp);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(SANPHAM sp, HttpPostedFileBase HinhAnhChinh, IEnumerable<HttpPostedFileBase> HinhAnhPhu, string[] delHinhAnhPhu)
        {
            sp.NgayCapNhat = DateTime.Now;
            string mainImgName = SaveImg(HinhAnhChinh, sp.HinhAnh);

            if (!string.IsNullOrEmpty(mainImgName))
                sp.HinhAnh = mainImgName;

            SanPhamBUS.Update(sp);

            if (HinhAnhPhu != null && HinhAnhPhu.Count() > 0)
            {
                foreach (var img in HinhAnhPhu)
                {
                    string imgName = SaveImg(img);
                    if (!string.IsNullOrEmpty(imgName))
                        HinhAnhSpBUS.Add(sp.ID, imgName);
                }
            }

            if (delHinhAnhPhu != null && delHinhAnhPhu.Count() > 0)
            {
                foreach (var img in delHinhAnhPhu)
                {
                    if (!string.IsNullOrEmpty(img))
                        HinhAnhSpBUS.Delete(sp.ID, img);
                }
            }

            ViewBag.Loai = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            ViewBag.NhaSX = new SelectList(NhaSanXuatBUS.DanhSach(), "ID", "Ten");
            ViewBag.HinhAnhPhu = HinhAnhSpBUS.DanhSach(sp.ID);
            return View(sp);
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using WebApplication1.Models.bus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
 
namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index(int? id)
        {
            if (id == null)
                return RedirectToAction("Index", "Home");
            else
            {
                var sp = SanPhamBUS.ChiTiet(id.Value);
                ViewBag.DSKM = SanPhamBUS.TimKiem("gia > khuyenmai", "", 1, 5).Items;
                ViewBag.CungLoai = SanPhamBUS.TimKiem("loai = " + sp.Loai, "", 1, 7).Items;
                ViewBag.HinhAnh = HinhAnhSpBUS.DanhSach(id.Value);
                ViewBag.BinhLuan = BinhLuanBUS.DanhSach(id.Value);
                return View(sp);
            }
        }
    }
}

WebApplication1/Areas/Admin/Views/ProductMng/Add.cshtml
@model ShopConnection.SANPHAM

@{
    ViewBag.Title = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="progressbar-heading grids-heading">
    <h2>Thêm sản phẩm</h2>
</div>

<div class="panel panel-widget forms-panel col-sm-8" style="float:none;margin:auto;">
    <div class="forms">
        <div class="form-grids widget-shadow" data-example-id="basic-forms">
            <div class="form-title">
                <h4>Thông tin :</h4>
            </div>
            <div class="form-body">
                @using (Html.BeginForm("Add", "ProductMng", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Ten, "Tên:")
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.Gia, "Giá bán:")
                            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.KhuyenMai, "Khuyến mãi (%):")
                            @Html.EditorFor(model => model.KhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.Loai, "Thuộc loại:")
                            @Html.DropDownList("Loai", null, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.NhaSX, "Nhà sản xuất:")
                            @Html.DropDownList("NhaSX", null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MoTa, "Mô tả:")
                        <textarea name="Mota" rows="8" class="form-control"></textarea>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThongTinThem, "Cấu hình:")
                        <textarea name="ThongTinThem" id="ThongTinThem"></textarea>
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.SoThangBaoHanh, "Số tháng bảo hành:")
                            @Html.EditorFor(model => model.SoThangBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.SoLuongTon, "Số lượng tồn:")
                            @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-control" for="HinhAnhChinh">Hình ảnh chính:</label>
                        <input type="file" name="HinhAnhChinh" class="img-upload" accept="image/*" />
                    </div>

                    <div class="form-group">
                        <label class="form-control" for="HinhAnhPhu">Hình ảnh phụ:</label>
                        <input type="file" name="HinhAnhPhu" class="img-upload" accept="image/*" multiple />
                    </div>

                    <div class="checkbox">
                        <label><input type="checkbox" name="LaSanPhamMoi" value="true"> Sản phẩm mới </label>
                        <input type="hidden" value="false" name="LaSanPhamMoi" />
                    </div>

                    <div class="checkbox">
                        <label><input type="checkbox" name="LaSanPhamHot" value="true"> Sản phẩm nổi bật </label>
                        <input type="hidden" value="false" name="LaSanPhamHot" />
                    </div>

                    <div class="checkbox">
                        <label><input type="checkbox" name="Khoa" value="true"> Khoá sản phẩm </label>
                        <input type="hidden" value="false" name="Khoa" />
                    </div>

                    <button type="submit" class="btn btn-default w3ls-button">Thêm</button>
                }
            </div>
            <table class="editpanel">
                <tr>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script src="~/Areas/Admin/Content/plugins/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('ThongTinThem');

</script>

WebApplication1/Areas/Admin/Views/ProductMng/Edit.cshtml
@model ShopConnection.SANPHAM

@{
    ViewBag.Title = "Sửa sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var HinhAnhPhu = ViewBag.HinhAnhPhu as IEnumerable<ShopConnection.HINHANHSP>;
}

<div class="progressbar-heading grids-heading">
    <h2>Sửa sản phẩm</h2>
</div>

<div class="panel panel-widget forms-panel col-sm-8" style="float:none;margin:auto;">
    <div class="forms">
        <div class="form-grids widget-shadow" data-example-id="basic-forms">
            <div class="form-title">
                <h4>Thông tin :</h4>
            </div>
            <div class="form-body">
                @using (Html.BeginForm("Edit", "ProductMng", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <div class="gallery-grids">
                            <div class="show-reel">
                                <div class="col-md-6 agile-gallery-grid">
                                    <div class="agile-gallery">
                                        <img src="/Content/images/products/@(Model.HinhAnh)" alt="@(Model.HinhAnh)" />
                                    </div>
                                </div>
                                @foreach (var img in HinhAnhPhu)
                                {
                                    <div class="col-md-3 agile-gallery-grid">
                                        <div class="agile-gallery">
                                            <img src="/Content/images/products/@(img.Ten)" alt="@(img.Ten)" />
                                            <div class="agileits-caption">
                                                <label class="form-control"><input type="checkbox" name="delHinhAnhPhu" value="@(img.Ten)" />  Xoá</label>
                                            </div>
                                        </div>
                                    </div>
                                }
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        @Html.LabelFor(model => model.Ten, "Tên:")
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.Gia, "Giá bán:")
                            @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.KhuyenMai, "Khuyến mãi (%):")
                            @Html.EditorFor(model => model.KhuyenMai, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.Loai, "Thuộc loại:")
                            @Html.DropDownListFor(x => x.Loai, null, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.NhaSX, "Nhà sản xuất:")
                            @Html.DropDownListFor(x => x.NhaSX, null, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MoTa, "Mô tả:")
                        <textarea name="Mota" rows="8" class="form-control">@(Model.MoTa ?? "")</textarea>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThongTinThem, "Cấu hình:")
                        <textarea name="ThongTinThem" id="ThongTinThem">@Html.Raw(Model.ThongTinThem)</textarea>
                    </div>

                    <div class="row">
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.SoThangBaoHanh, "Số tháng bảo hành:")
                            @Html.EditorFor(model => model.SoThangBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group col-xs-12 col-sm-6">
                            @Html.LabelFor(model => model.SoLuongTon, "Số lượng tồn:")
                            @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="form-control" for="HinhAnhChinh">Hình ảnh chính:</label>
                        <input type="file" name="HinhAnhChinh" class="img-upload" accept="image/*" />
                        <input type="hidden" name="HinhAnh" value="@Model.HinhAnh" />
                    </div>

                    <div class="form-group">
                        <label class="form-control" for="HinhAnhPhu">Hình ảnh phụ:</label>
                        <input type="file" name="HinhAnhPhu" class="img-upload" accept="image/*" multiple />
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LaSanPhamMoi, "Sản phẩm mới:")
                        @Html.EditorFor(model => model.LaSanPhamMoi, null)
                        <input type="hidden" value="false" name="LaSanPhamMoi" />
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LaSanPhamHot, "Sản phẩm nổi bật:")
                        @Html.EditorFor(model => model.LaSanPhamHot, null )
                        <input type="hidden" value="false" name="LaSanPhamHot" />
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Khoa, "Khoá sản phẩm:")
                        @Html.EditorFor(model => model.Khoa, null)
                        <input type="hidden" value="false" name="Khoa" />
                    </div>

                    <button type="submit" class="btn btn-default w3ls-button">Sửa</button>
                }
            </div>
            <table class="editpanel">
                <tr>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<script src="~/Areas/Admin/Content/plugins/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('ThongTinThem');
    $(window).load(function () {
        $.fn.lightspeedBox();
    });
</script>

WebApplication1/Areas/Admin/Views/ProductMng/Index.cshtml
@model PetaPoco.Page<dynamic>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var ds = Model.Items;
    int range = 3;
    int current = 0, i = 0 ;
    WebGrid grid = new WebGrid(source: ds, rowsPerPage: 50);
}

<div class="progressbar-heading grids-heading">
    <h2>Danh sách sản phẩm</h2>
</div>

@Html.ActionLink("Thêm sản phẩm", "Add", "ProductMng")

<div class="panel panel-widget forms-panel col-sm-12 col-md-12" style="float:none;margin:auto;">
    <div class="agile-tables">
        <div class="w3l-table-info">
            <table id="table-breakpoint">
                <thead>
                    <tr>
                        <th>Ảnh</th>
                        <th>ID</th>
                        <th>Tên</th>
                        <th>Giá</th>
                        <th>Số lượng tồn</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ds)
                    {
                        <tr>
                            <td><a class='product-detail-box' href='#product@(item.ID)-detail'><img class="img-responsive" src='/Content/images/products/@(item.HinhAnh)' title='Click for quick information' alt='@(item.Ten)' width="150"></a></td>
                            <td>@item.ID</td>
                            <td>@item.Ten</td>
                            <td>@item.Gia.ToString("N0")</td>
                            <td>@item.SoLuongTon</td>
                            <td><a href='@Url.Action("Edit", "ProductMng", new { id = item.ID })'>Sửa</a> | <a href='@Url.Action("Index", "Product", new { area="", id = item.ID })'>Chi tiết</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="pull-right">
        <ul class="pagination">
            @{
                if (Model.CurrentPage > range + 1)
                {
                    <li class="prev"><a href="@Url.Action("Index","ProductMng", new {page = 1})"><i class="fa">Trang đầu</i></a></li>
                }

                current = (int)Model.CurrentPage - range;
                if (current <= 0)
                {
                    current = 1;
                }

                for (i = current; i <= Model.CurrentPage + range && i <= Model.TotalPages; i++)
                {
                    if (i == Model.CurrentPage)
                    {
                        <li class="active"><a href="@Url.Action("Index", "ProductMng", new { page = i })">@i</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Index", "ProductMng", new { page = i })">@i</a></li>
                    }
                }

                if (Model.CurrentPage < Model.TotalPages - range)
                {
                    <li class="next"><a href="@Url.Action("Index", "ProductMng", new {page = Model.TotalPages })"><i class="fa">Trang cuối</i></a></li>
                }
            }
        </ul><!-- /.list-inline -->
    </div>
</div>


@foreach (var item in ds)
{
    <div style="display:none">
        <div id="product@(item.ID)-detail" class="product-detail-box">
            <div class="row">
                <div class="col-sm-12 col-md-5">
                    <img class="img-responsive" alt="@item.Ten" src="/Content/images/products/@(item.HinhAnh)">
                </div>
                <div class="col-sm-12 col-md-7">
                    <h3>Chi tiết</h3>
                    <ul>
                        <li>Mã: @item.ID</li>
                        <li>Tên: @item.Ten</li>
                        <li>Giá: @item.Gia.ToString("N0")đ</li>
                        <li>Khuyến mãi: @(item.KhuyenMai)%</li>
                        <li>Loại: @item.TenLoai</li>
                        <li>Nhà sản xuất: @item.TenNSX</li>
                        <li>Bảo hành: @item.SoThangBaoHanh tháng</li>
                        <li>Số lượng tồn: @item.SoLuongTon cái</li>
                        <li>Lượt xem: @item.LuotXem</li>
                        <li>Lượt bình chọn: @item.LuotBinhChon</li>
                        <li>Lượt bình luận: @item.LuotBinhLuan</li>
                        <li>Lượt mua: @item.LuotMua</li>
                        <li>Số sao: @item.SoSao</li>
                        <li>Sản phẩm HOT: @(item.LaSanPhamHot ? "Y" : "N")</li>
                        <li>Sản phẩm mới: @(item.LaSanPhamMoi ? "Y" : "N")</li>
                        <li>Khoá: @(item.Khoa ? "Y" : "N")</li>
                        <li>Lần cập nhật cuối: @item.NgayCapNhat</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

<script>$(document).ready(function () {
    $(document).ready(function () {
        $("a.product-detail-box").fancybox({
            'transitionIn': 'elastic',
            'transitionOut': 'elastic',
            'speedIn': 600,
            'speedOut': 200,
            'overlayShow': false
        });

        $('.product-detail-box table').attr('class', 'table');

        $('#table-breakpoint').basictable({
            breakpoint: 768,
        });
    });
});</script>