WebApplication1/Areas/Admin/Controllers/ProducerMngController.cs
using WebApplication1.Models.bus;
using ShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProducerMngController : Controller
    {
        public ActionResult Index()
        {
            var ds = NhaSanXuatBUS.DanhSachFull();
            return View(ds);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(NHASANXUAT nsx, HttpPostedFileBase imgLogo)
        {
            string mainImgName = SaveImg(imgLogo);

            if (!string.IsNullOrEmpty(mainImgName))
                nsx.Logo = mainImgName;

            NhaSanXuatBUS.Add(nsx);
            return View();
        }

        [NonAction]
        public string SaveImg(HttpPostedFileBase img, string origin = "")
        {
            string name = "";
            if (img != null && img.ContentLength > 0)
            {
                if (string.IsNullOrEmpty(origin))
                    name = Guid.NewGuid().ToString() + img.FileName.Substring(img.FileName.LastIndexOf('.'));
                else
                    name = origin;
                var path = System.IO.Path.Combine(Server.MapPath("~/Content/images/brands/"), name);
                img.SaveAs(path);
            }
            return name;
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var nsx = NhaSanXuatBUS.ChiTiet(id.Value);
            return View(nsx);
        }

        [HttpPost]
        public ActionResult Edit(NHASANXUAT nsx, HttpPostedFileBase imgLogo)
        {
            string mainImgName = SaveImg(imgLogo);

            if (!string.IsNullOrEmpty(mainImgName))
                nsx.Logo = mainImgName;

            NhaSanXuatBUS.Update(nsx);
            return View(nsx);
        }
    }
}

WebApplication1/Areas/Admin/Views/ProducerMng/Add.cshtml
@model ShopConnection.NHASANXUAT
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="progressbar-heading grids-heading">
    <h2>Thêm nhà sản xuất</h2>
</div>

<div class="panel panel-widget forms-panel col-sm-8" style="float:none;margin:auto;">
    <div class="forms">
        <div class="form-grids widget-shadow" data-example-id="basic-forms">
            <div class="form-title">
                <h4>Thông tin :</h4>
            </div>
            <div class="form-body">
                @using (Html.BeginForm("Add", "ProducerMng", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    
                        <div class="form-group">
                            @Html.LabelFor(model => model.Ten, "Tên:")
                            @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ThongTin, "Thông tin:")
                            <textarea name="ThongTin" rows="8" class="form-control"></textarea>
                        </div>

                        <div class="form-group">
                            <label class="form-control" for="Logo">Logo:</label>
                            <input type="file" name="imgLogo" class="img-upload" accept="image/*" />
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Khoa, "Khoá:")
                            <div class="checkbox">
                                @Html.EditorFor(model => model.Khoa)
                            </div>
                        </div>

                        <button type="submit" class="btn btn-default w3ls-button">Thêm</button>
                }
            </div>
        </div>
    </div>
</div>

WebApplication1/Areas/Admin/Views/ProducerMng/Edit.cshtml
@model ShopConnection.NHASANXUAT
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="progressbar-heading grids-heading">
    <h2>Sửa nhà sản xuất</h2>
</div>

<div class="panel panel-widget forms-panel col-sm-8" style="float:none;margin:auto;">
    <div class="forms">
        <div class="form-grids widget-shadow" data-example-id="basic-forms">
            <div class="form-title">
                <h4>Thông tin :</h4>
            </div>
            <div class="form-body">
                @using (Html.BeginForm("Edit", "ProducerMng", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Ten, "Tên:")
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThongTin, "Thông tin:")
                        <textarea name="ThongTin" rows="8" class="form-control">@(Model.ThongTin ?? "")</textarea>
                    </div>

                    <div class="form-group">
                        <label class="form-control" for="Logo">Logo:</label>
                        <input type="file" name="imgLogo" class="img-upload" accept="image/*" />
                        <input type="hidden" value="@Model.Logo" />
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Khoa, "Khoá:")
                        @Html.EditorFor(model => model.Khoa)
                    </div>

                    <button type="submit" class="btn btn-default w3ls-button">Sửa</button>
                }
            </div>
        </div>
    </div>
</div>

WebApplication1/Areas/Admin/Views/ProducerMng/Index.cshtml
@model IEnumerable<ShopConnection.NHASANXUAT>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var ds = Model.ToList();
    WebGrid grid = new WebGrid(source: ds, rowsPerPage: 50);
}

<div class="progressbar-heading grids-heading">
    <h2>Danh sách nhà sản xuất</h2>
</div>

@Html.ActionLink("Thêm nhà sản xuất", "Add", "ProducerMng")

<div class="panel panel-widget forms-panel col-sm-12 col-md-12" style="float:none;margin:auto;">
    <div class="agile-tables">
        <div class="w3l-table-info">
            <table id="table-breakpoint">
                <thead>
                    <tr>
                        <th>Logo</th>
                        <th>ID</th>
                        <th>Tên</th>
                        <th>Thông tin</th>
                        <th>Trạng thái</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ds)
                    {
                        <tr>
                            <td><img class="img-responsive" src='/Content/images/brands/@(item.Logo)' alt='@(item.Ten)' width="150"></td>
                            <td>@item.ID</td>
                            <td>@item.Ten</td>
                            <td>@item.ThongTin</td>
                            <td>@(item.Khoa ? "Đang khoá" : "Mở")</td>
                            <td><a href='@Url.Action("Edit", "ProducerMng", new { id = item.ID })'>Sửa</a> | <a href='#'>Danh sách sản phẩm</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function () {
        $('.product-detail-box table').attr('class', 'table');

        $('#table-breakpoint').basictable({
            breakpoint: 768,
        });
    });
});</script>