WebApplication1/Areas/Admin/Controllers/CategoryMngController.cs
using WebApplication1.Models.bus;
using ShopConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryMngController : Controller
    {
        public ActionResult Index()
        {
            var ds = LoaiSanPhamBUS.DanhSachFull();
            return View(ds);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Parent = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            return View();
        }

        [HttpPost]
        public ActionResult Add(LOAISANPHAM lsp)
        {
            LoaiSanPhamBUS.Add(lsp);
            ViewBag.Parent = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            var lsp = LoaiSanPhamBUS.ChiTiet(id.Value);
            ViewBag.Parent = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            return View(lsp);
        }

        [HttpPost]
        public ActionResult Edit(LOAISANPHAM lsp)
        {
            LoaiSanPhamBUS.Update(lsp);
            ViewBag.Parent = new SelectList(LoaiSanPhamBUS.DanhSach(), "ID", "Ten");
            return View();
        }
    }
}

WebApplication1/Controllers/CategoryController.cs
using WebApplication1.Models.bus;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        public ActionResult Index(int? id, int? page)
        {
            if (id == null)
                return RedirectToAction("Index", "Home");
            else
            {
                page = page ?? 1;
                ViewBag.ChiTiet = LoaiSanPhamBUS.ChiTiet(id.Value);
                ViewBag.DSLsp = LoaiSanPhamBUS.DanhSach().ToList();
                ViewBag.DSNsx = NhaSanXuatBUS.DanhSach();
                var dssp = SanPhamBUS.TimKiem("loai = " + id.Value, "", page.Value, 20);
                return View(dssp);
            }
        }
    }
}

WebApplication1/Areas/Admin/Views/CategoryMng/Add.cshtml
@model ShopConnection.LOAISANPHAM

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="progressbar-heading grids-heading">
    <h2>Thêm loại sản phẩm</h2>
</div>

<div class="panel panel-widget forms-panel col-sm-8" style="float:none;margin:auto;">
    <div class="forms">
        <div class="form-grids widget-shadow" data-example-id="basic-forms">
            <div class="form-title">
                <h4>Thông tin :</h4>
            </div>
            <div class="form-body">
                @using (Html.BeginForm("Add", "CategoryMng", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    
                    <div class="form-group">
                        @Html.LabelFor(model => model.Ten, "Tên: ")
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Parent, "Gốc:")
                        @Html.DropDownListFor(x => x.Parent, null, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Khoa, "Khoá")
                        @Html.EditorFor(model => model.Khoa)
                    </div>

                    <button type="submit" class="btn btn-default w3ls-button">Thêm</button>
                }
            </div>
        </div>
    </div>
</div>


                

WebApplication1/Areas/Admin/Views/CategoryMng/Edit.cshtml
@model ShopConnection.LOAISANPHAM

@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="progressbar-heading grids-heading">
    <h2>Sửa loại sản phẩm</h2>
</div>

<div class="panel panel-widget forms-panel col-sm-8" style="float:none;margin:auto;">
    <div class="forms">
        <div class="form-grids widget-shadow" data-example-id="basic-forms">
            <div class="form-title">
                <h4>Thông tin :</h4>
            </div>
            <div class="form-body">
                @using (Html.BeginForm("Edit", "CategoryMng", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Ten, "Tên: ")
                        @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Parent, "Gốc:")
                        @Html.DropDownListFor(x => x.Parent, null, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Khoa, "Khoá")
                        @Html.EditorFor(model => model.Khoa)
                    </div>

                    <button type="submit" class="btn btn-default w3ls-button">Sửa</button>
                }
            </div>
        </div>
    </div>
</div>

WebApplication1/Areas/Admin/Views/CategoryMng/Index.cshtml
@model IEnumerable<dynamic>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var ds = Model.ToList();
    WebGrid grid = new WebGrid(source: ds, rowsPerPage: 50);
}

<div class="progressbar-heading grids-heading">
    <h2>Danh sách loại sản phẩm</h2>
</div>

@Html.ActionLink("Thêm loại sản phẩm", "Add", "CategoryMng")

<div class="panel panel-widget forms-panel col-sm-12 col-md-12" style="float:none;margin:auto;">
    <div class="agile-tables">
        <div class="w3l-table-info">
            <table id="table-breakpoint">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên</th>
                        <th>Gốc (Tên / ID)</th>
                        <th>Trạng thái</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in ds)
                    {
                        <tr>
                            <td>@item.ID</td>
                            <td>@item.Ten</td>
                            <td>@item.ParentName / @item.Parent</td>
                            <td>@(item.Khoa ? "Đang khoá" : "Mở")</td>
                            <td><a href='@Url.Action("Edit", "CategoryMng", new { id = item.ID })'>Sửa</a> | <a href='@Url.Action("Index", "Category", new { area="", id = item.ID })'>Danh sách sản phẩm</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
$(document).ready(function () {
        $('.product-detail-box table').attr('class', 'table');

        $('#table-breakpoint').basictable({
            breakpoint: 768,
        });
    });
});</script>